language: node_js
# env:
#   global:
#     secure: r79u0FiesJ5sFhD0b+3YUtPk6Nw1zG3rmSiah9c1y0VZo7yXDaq6M8TR+mhIZ5Zg8y2Qr38Qp4zRaGzQy/MOVSyvpKSg8Smfe3U7b+bsOKNHF1sGOFTSutpTbJ44MYF6pHLJvTpCmtf8/286DLPIFd1FnVBbd8KU0ouOlCLWAhDD5Lro0wmJjz7/FuIsGiCaCvMDq7jisdni4MwcPQp2jGgWIhSMSd3lrDOt0nI/+xyQ3rCxqNLcnDvU40BDGQ1mrGX8C9lGF5iy23KhA/W0epmmXmnmhsTYfB30DyGUK5CWnmY0yCz1mpv7p/BFWeT936bKgl/mpNkA1cQMHw0KBP/FtPNXght8UWSlDCSn/Hf/AmylH/T5e9/D52LBkOu9+q0B+6fMp/uWaGEzqgpOJrfE9XBOtUqfZWWVLoELCvAnV3WbGaQL7o641HQMqVB3bHG2CCsHc2qktvIbMvU1jSbjQm7U8EQ5E4/LBJ3KTVa9OkU+/12MFFnmZ7F4KyIQGsoVlZX6ZTAA0VAqtUIHUlIIHZevrt1atNvc2FCakxIV4dYubP2OtFcKgLbHrZznbOHoewTcPVXCYQpdeTVqE4ZRVyCrveJznudkCT//fzh9cIRMO+5hCnwu1+TJM1lqzl1JSjzeOIGUwegHgzyJjS8UcMfKNIOPRqu+bLvCEK8=

node_js:
- '10.15.1'
# - '8.10.0'
cache: yarn
before_install:
# - chmod 755 ./deploy.sh
install:
- yarn install
before_script:
# - git config --global user.email "travis@travis-ci.org"
# - git config --global user.name "Travis"
script:
# - chmod +x ./deploy-ghpages.sh
- yarn build # Change this script to run your production build command
# - chmod +x ./deploy.sh
# - "./deploy.sh"
after_success:
# this "deploy.sh" has code to deploy files generated from vue production build
# - gulp deploy
# - "./deploy.sh"
after_failure:
after_script:
before_deploy:
    # env:
    #     - GITHUB_TOKEN = 8f0230cb4dab3b92898ace43abc85e0c34387d91
deploy:
# Standard GH-Pages Deploy  
  provider: pages
  skip-cleanup: true
#   github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local_dir: dist # Change this to your build directory
  on:
    branch: master
after_deploy:  
